# Site settings
title: Eric Rexstad, Research Fellow
email: eric.rexstad@st-andrews.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Built in Jekyll, maintained on Github
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erex.github.io" # the base hostname & protocol for your site
twitter_username: ericrexstad
github_username:  erex

# Build settings
markdown: kramdown
